learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
]

learning_log/learning_logs/urls.py
from django.urls import path
from. import views

app_name = 'learning_logs'

urlpatterns = [
    path('', views.index, name='index'),
    path('topiks/', views.topiks, name='topiks')
]

learning_log/learning_logs/models.py
from django.db import models

# Create your models here.
class Topik(models.Model):
    """A topic the user is learning about"""
    #text adında bir charfield tanımlıyoruz. bu veri tabanında bir sütun oluşturacak. max karakteri 200
    text =models.CharField(max_length=200)

    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


# topik (konular) altında belirli bir girdi girebilmek için Entry isimli model
class Entry(models.Model):
    """something specific learned about a topik"""
    topik =models.ForeignKey(Topik, on_delete=models.CASCADE)
    text =models.TextField()
    date_added =models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return f"{self.text[:50]}..."

learning_log/learning_logs/views.py
from django.shortcuts import render

from .models import Topik


# Create your views here.
def index(request):
    """The home page for learning log."""
    return render(request, 'learning_logs/index.html')


def topiks(request):
    topiks = Topik.objects.order_by('date_added')
    context = {'topiks': topiks}
    return render(request, 'learning_logs/topiks.html', context)

learning_log/learning_logs/templates/learning_logs/base.html
<p xmlns="http://www.w3.org/1999/html">
  <a href="{% url 'learning_logs:index' %}">
      <img src="http://www.clker.com/cliparts/b/e/e/e/11949839881243335407note.svg.med.png"
          alt="learnnig log" width="30" height="30">
      Learning Log</a>
    <a href="{% url 'learning_logs:topiks' %}">Topiks</a>

</p>
{% block content %}{%endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
</head>
<body>
{% extends 'learning_logs/base.html' %}
{% block content %}

<p>learning log help you keep track of your learning,for any topic you're learning about.</p>
{% endblock content %}
</body>
</html>

learning_log/learning_logs/templates/learning_logs/topiks.html
{% extends 'learning_logs/base.html' %}
{% block content %}

<h1>Topiks: </h1>
<ul>
  {% for topik in topiks %}
      <li>{{ topik }}</li>
  {% empty %}
     <li>No topiks have been added yet. </li>
  {% endfor %}
</ul>


{% endblock content %}